//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDoc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpenDocEntities : DbContext
    {
        public OpenDocEntities() : base("name=OpenDocEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aduana> Aduana { get; set; }
        public virtual DbSet<BL> BL { get; set; }
        public virtual DbSet<Contenedor> Contenedor { get; set; }
        public virtual DbSet<EstadoContenedor> EstadoContenedor { get; set; }
        public virtual DbSet<Incidente> Incidente { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<ModoTransporte> ModoTransporte { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Sealing> Sealing { get; set; }
        public virtual DbSet<TipoBL> TipoBL { get; set; }
        public virtual DbSet<TipoContenedor> TipoContenedor { get; set; }
        public virtual DbSet<TipoMercancia> TipoMercancia { get; set; }
        public virtual DbSet<TipoPaquete> TipoPaquete { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Viaje> Viaje { get; set; }
        public virtual DbSet<Puerto> Puerto { get; set; }
    }
}
