//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public string ID { get; set; }
        public string nom_pais { get; set; }
        public System.DateTime fec_crea { get; set; }
        public string usu_crea { get; set; }
    }
}
